### ISSUE TITLE
Is there a way to convert the recorded .raw file to a .wav file?

### ISSUE THREAD

**Issue by arnavb** [Streampunk/naudiodon#11]
I realize that the README here says:

> Note that this produces a raw audio file - wav headers would be required to create a wav file.

However, do you have any idea for how I should go about this? (Using JS, not a command line tool such as SoX, unless there is a wrapper for it)

**Comment by grahamtallen** [comment]
I used Lame https://www.npmjs.com/package/lame for mp3 encoding, I have seen a couple examples  of people using .wav but I haven't tried them out yet.

**Comment by sparkpunkd** [comment]
naudiodon was written to support an IoT framework written in Javascript for media stream processing. That framework includes a WAV file writer. You would have to modify the code a bit but it is a possible starting point:

https://github.com/Streampunk/node-red-contrib-dynamorse-file-io/blob/master/nodes/24-wav-out.js

**Comment by jakelacey2012** [comment]
Just to post an example to help people.

```javascript
var fs = require('fs');
var portAudio = require('naudiodon');
var lame = require('lame');  //  https://www.npmjs.com/package/lame 

var ai = new portAudio.AudioInput({
  channelCount: 2,
  sampleFormat: portAudio.SampleFormat16Bit,
  sampleRate: 44100,
  deviceId : -1 // Use -1 or omit the deviceId to select the default device
});

// create the Encoder instance
var encoder = new lame.Encoder({
  // input
  channels: 2,        // 2 channels (left and right)
  bitDepth: 16,       // 16-bit samples
  sampleRate: 44100,  // 44,100 Hz sample rate
 
  // output
  bitRate: 128,
  outSampleRate: 22050,
  mode: lame.STEREO // STEREO (default), JOINTSTEREO, DUALCHANNEL or MONO
});

var ws = fs.createWriteStream('rawAudio.mp3');

ai.on('error', err => console.error);

process.stdin.pipe(encoder);

ai.pipe(encoder);
ai.start();

encoder.pipe(ws);

```
This is a way, but probably not the best way.

**Comment by jakelacey2012** [comment]
Hey @Aweponken , I can't see any specific reason looking back its "just" connecting some pipes. I think I was just trying to get across that it was a quick hacky example.

**Comment by Aweponken** [comment]
> Hey @Aweponken , I can't see any specific reason looking back its "just" connecting some pipes. I think I was just trying to get across that it was a quick hacky example.

I see, thanks for the answer!

**Comment by scriptorian** [comment]
Closing this issue.
