### ISSUE TITLE
Does this binding support full-duplex (simultaneous input/output) PortAudio streams?

### ISSUE THREAD

**Issue by gschmottlach-xse** [Streampunk/naudiodon#13]
I see that it supports, separately, both input and output streams. What is not clear is whether it support full-duplex (e.g. both input/output) audio streams? Trying to create separate Input and Output audio streams with the same device ID fails. Can this be easily achieved via some other mechanism?

**Comment by scriptorian** [comment]
Yes it does - I have tested it on my laptop and can create 'howl-round' between my microphone and speakers. Have you checked the device ids for the input and output devices you are trying to use?

**Comment by gschmottlach-xse** [comment]
Here's the issue, I suspect your microphone and speakers appear as two separate device IDs in PortAudio. In my scenario, I have a single device (one device ID) that has *both* input and output channels. Opening it up for input prevents me from opening the (same) device for output. I receive an error in this case basically telling me the device is already in use. What it seems I need is an AudioInputOutput that uses the same device ID. The lower-level PortAudio API does not seem to preclude this configuration. Have you seen otherwise, and if so, can you point me at an example?

Thanks . . .

**Comment by scriptorian** [comment]
My apologies for not reading your comments correctly - I've just reviewed the documentation and I now see what you mean - portaudio supports full duplex on a device but it is something I didn't consider in my implementation. So the correct answer is: No, this binding doesn't support full-duplex PortAudio streams.
To add support, the C++ addon would need to be refactored to offer a device that could be input, output or full duplex when it initialises. The binding could then be modified to offer a node Duplex stream.

**Comment by Jexah** [comment]
I can't get piping from input to output working on Windows 10.

Here are my devices:

Input:
```
{ id: 13,
  name: 'Stereo Mix (Realtek High Definition Audio)',
  maxInputChannels: 2,
  maxOutputChannels: 0,
  defaultSampleRate: 48000,
  defaultLowInputLatency: 0.003,
  defaultLowOutputLatency: 0,
  defaultHighInputLatency: 0.01,
  defaultHighOutputLatency: 0,
  hostAPIName: 'Windows WASAPI' }
```

Output:
```
{ id: 8,
  name: 'Speakers (Realtek High Definition Audio)',
  maxInputChannels: 0,
  maxOutputChannels: 2,
  defaultSampleRate: 192000,
  defaultLowInputLatency: 0,
  defaultLowOutputLatency: 0.003,
  defaultHighInputLatency: 0,
  defaultHighOutputLatency: 0.01,
  hostAPIName: 'Windows WASAPI' }
```

My code: 

```
let devices = portAudio.getDevices();

let stereoMix = devices.find(
  d => d.name === "Stereo Mix (Realtek High Definition Audio)"
);

let speakers = devices.find(
  d => d.name === "Speakers (Realtek High Definition Audio)"
);

console.log(stereoMix);
console.log(speakers);

var ao = new portAudio.AudioOutput({
  channelCount: 2,
  sampleFormat: portAudio.SampleFormat16Bit,
  sampleRate: 192000, //48000,
  deviceId: speakers.id //headset.id
});

var ai = new portAudio.AudioInput({
  channelCount: 2,
  sampleFormat: portAudio.SampleFormat16Bit,
  sampleRate: 48000,
  deviceId: stereoMix.id
});

ai.pipe(ao);

ao.start();
console.log("ao started");
ai.start();
console.log("ai started");
```

I get the following error:
```
C:\Users\<user>\Desktop\<app>\node_modules\naudiodon\index.js:75
  this.start = () => this.AudioOutAdon.start();
                                       ^

Error: Could not start output stream: Unanticipated host error
    at AudioOutput.start (C:\Users\<user>\Desktop\<app>\node_modules\naudiodon\index.js:75:40)
    at Object.<anonymous> (C:\Users\<user>\Desktop\<app>\index.js:45:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

**Comment by gschmottlach-xse** [comment]
For those who are interested . . . 

I've created a [fork](https://github.com/gschmottlach-xse/naudiodon) that implements bidirectional streams and PortAudio ASIO support on Windows platforms. On that platform the module will download the Steinberg ASIO SDK and build PortAudio from sources. As a result it requires a development environment for compiling Node.js addons. I'd recommend globally installing the [Windows-build-tools](https://www.npmjs.com/package/windows-build-tools) module into your Node.js environment to support the installation of my fork.

**Comment by scriptorian** [comment]
I have just pushed a big update to naudiodon. This version has support for bidirectional streams - thanks very much for pointing to the omission! I have done the refactor I suggested but since I don't have a bidirectional card I can't test this. I have not investigated ASIO support.
Jexah: please take a look at scratch/smokeLoop.js.
I will close this issue.
