### ISSUE TITLE
Program crashes when using AudioInput

### ISSUE THREAD

**Issue by ynx0** [Streampunk/naudiodon#15]
I am running the example file `inputToFile.js`. However, when I run `node inputToFile.js`, it simply outputs the following: 
`Input audio options: default device, sample rate 44100, channels 2, bits per sample 16, max queue 2`
And exits with no indication of what happened.

Using the following command `forever --spinSleepTime 1 inputToFile.js`, 
I get the following message:
`Forever detected script exited with code: 3221225477` (0xC0000005)

Apparently this is a windows error similar to SEGFAULT.
Any one know how to fix this?

**Comment by scriptorian** [comment]
I have just pushed a big update to naudiodon that includes a crash handler that may give more information. Hopefully the update will have also fixed the crash!
Closing this issue for now.

**Comment by ynx0** [comment]
Thank you @scriptorian
