### ISSUE TITLE
How would I record system audio.

### ISSUE THREAD

**Issue by jakelacey2012** [Streampunk/naudiodon#16]
Forgive my ignorance if this is obvious but how would you record system audio?

I tried creating an instance of `AudioOutput` but I could spot anything on the stream.

**Comment by jakelacey2012** [comment]
@scriptorian is this something you would be able to help with? or know somebody who can?

**Comment by scriptorian** [comment]
This doesn't seem to be supported as standard. I've done a quick search for loopback recording with portaudio and there is a suggestion that it is possible with WASAPI on Windows and with different tricks on other platforms - it looks troublesome though. Is there a good reason why you can't wire your output jack back to your input jack and record from that?

**Comment by scriptorian** [comment]
Fair enough!
This software supports streaming _from_ audio input devices and streaming _to_ audio output devices, based on features of the portAudio project. Unfortunately that project doesn't appear to allow me to support streaming _from_ an output device.

**Comment by jakelacey2012** [comment]
Appreciate the help, going to keep on look I'll let you know what I find. wasn't aware of the term loopback recording so that should help.

**Comment by scriptorian** [comment]
Closing this for now.

**Comment by dustinkerstein** [comment]
Just curious if anyone found a good solution for capturing the system audio. I'm looking to do the same.

**Comment by sntxerror** [comment]
Reopen maybe?

**Comment by stevenlafl** [comment]
@sntxerror Yes, it should be reopened, this was pulled 2022 - https://github.com/PortAudio/portaudio/pull/672 . As per last comment on there, the newer version of PortAudio should contain a "virtual" device. It does look like the "latest" version of PortAudio is used with naudiodon, yet does not show up in the list. I suspect that we'd have to wait for a proper release or create a dev branch for this project.

@scriptorian Any thoughts here?

**Comment by 64jcl** [comment]
Was hoping someone could do this so that the virtual devices for outputs are listed as inputs in naudiodon seeing that PortAudio supports this already. Perhaps someone can point to the right place to do the change in the library?

**Comment by stevenlafl** [comment]
@64jcl I have tried to use this library (and vanilla PortAudio) with zero success,
using the instructions for PortAudio which says you can do it easily by
simply not specifying an input device. The desktop is not even listed in
the input devices, and I cannot use the current playback device as a
recording device.

The solution I used to get around this is to just not use it, at all.
Instead, I am using Electron to capture system audio, with desktopCapturer.
Not lightweight by any means, but luckily my use case already needed a GUI.
If you're trying to do it via CLI, I have not yet found a solution that is
available, which is frustrating beyond words.
