### ISSUE TITLE
Problems when installing on Windows

### ISSUE THREAD

**Issue by dotkim** [Streampunk/naudiodon#19]
Did a fresh install of windows yesterday(2018-12-06) and were having some issues installing this module.
System info:
Windows 10 Pro 64-bit
Version	10.0.17134 Build 17134 (1803)

I installed nodejs, python2, vscode, git and github desktop on the fresh install. Albeit that i did get other errors before i reinstalled.
There seems to be some unmentioned prerequesites for this module, and im not sure if you are aware of this?
First i had issues because i had python3 and not python2 installed(**this was before i reinstalled windows!**)
**You can see the first error i got here:**
`C:\Github\hue-controller>npm install --save naudiodon
> naudiodon@0.4.7 install C:\Github\hue-controller\node_modules\naudiodon
> node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\knerl\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd C:\Github\hue-controller\node_modules\naudiodon
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN hue-controller@1.0.0 No description
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! naudiodon@0.4.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the naudiodon@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\knerl\AppData\Roaming\npm-cache\_logs\2018-12-06T17_36_43_427Z-debug.log`

This should be fixed by installing python2 and having it in your PATH. I am not sure if you need to remove python3 from PATH before this will work.

**The second error goes something like this:**
`MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".`
The solution for this seems to be that you either have to install a redist that supports the mentioned version. Or you can download and install Visual Studio Community 2017 and add atleast one of or both these Workloads: .NET Desktop Development and Desktop Development with C++.
I added both.

After that the installation worked perfectly with no issues.

**Comment by sparkpunkd** [comment]
This looks like an issue with your system setup for building native addons ... and the fact that our instructions are not clear about this. We have done better with other modules.

See https://github.com/nodejs/node-gyp for details of setting up a system for building native modules.

I will improve the instructions before closing this issue.

**Comment by dotkim** [comment]
Yea, i see now that i should have been able to find that with a little more research.
Thanks for taking your time and answering :)!

**Comment by sparkpunkd** [comment]
Instructions improved.
