### ISSUE TITLE
Update the README with a list of available events and methods

### ISSUE THREAD

**Issue by lockykeaney** [Streampunk/naudiodon#20]
I was hoping to get a bit more of an idea of the event handlers that I can hook into.

For example, I want to created a recorder that starts whenever an audio signal is received from a usb device. Something like: 

```
ai.on('audioSignal', () => {
    // Start recording
}
```

Is there anything like that in portAudio? Or is that more something I would have to create an wrapper around the USB audio interface?

**Comment by scriptorian** [comment]
I believe the example file smokeLoop in the scratch folder answers the specific requirement you show for starting recording. The index.js file shows other events that you can listen for and the Node.js Streams documentation should help with any I am not using. I am closing this issue.
