### ISSUE TITLE
Can't enumerate supported hosts

### ISSUE THREAD

**Issue by thomasjwebb** [Streampunk/naudiodon#23]
There doesn't appear to be any wrapping of `Pa_GetHostApiCount` and `Pa_GetHostApiInfo`, which would allow me to get a list of the supported host apis and the default devices.

**Comment by scriptorian** [comment]
I am happy to look into exposing these two, it should be straightforward. Do you know whether having these two functions implemented is likely to lead you to finding more debits in the binding? For instance I don't provide any support for `hostApiSpecificStreamInfo` in `PaStreamParameters` as it isn't clear to me how to expose this. Please share any thoughts before I dive in!

**Comment by thomasjwebb** [comment]
Thanks for looking into it! I believe this is useful even without the api specific bindings. At the very least it lets you know what the api’s default ports are.

**Comment by thomasjwebb** [comment]
After your new version this feature works for me. Thanks!
