### ISSUE TITLE
No support for IEEE Sample Format.

### ISSUE THREAD

**Issue by ncgreco1440** [Streampunk/naudiodon#32]
I have a small script just loading in a single .wav file, mostly just a copy and paste from the README and the sound quality that outputs to my speakers is terrible. It's mostly screeching. 

I've confirmed that the audio file was saved at 44100 Hz with 32 Bit Float (IEEE), 2 channels. So I've set up the outOptions accordingly. 

```
var ao = new portAudio.AudioIO({
    outOptions: {
      channelCount: 2,
      sampleFormat: portAudio.SampleFormat32Bit,
      sampleRate: 44100,
      deviceId: -1 // Use -1 or omit the deviceId to select the default device
    }
});
````

The only way I could get the audio to behave nicely was to convert it to 16 Bit and then change the sampleFormat to SampleFormat16Bit. Is this intended by this library? Or is there some lower level detail that I am missing? Playing this same audio file through something like Audacity sounds just fine. 

---
### Edit 

So from my understanding, this library is expecting Signed 32 Bit Integers, not floats at all. Yikes!

Confirmed within PaContext.cc Line 226, the switch statement looks for a parameter of 32 and then assigns a Sample Format of paInt32 to the context. This lib should be able to distinguish between 32 Bit Int and 32 Bit Float which could mean a more robust parameter coming in from the node side or a new implementation of enums here that map to a wider range of PaSampleFormat enums.

---

**Comment by scriptorian** [comment]
Hi, thanks for the feedback and analysis!
The underlying library appears to support floating point samples but I have missed passing it through the binding. It should be a straightforward fix.
Is it possible for you to share a representative audio file so that I can test the change ?

**Comment by ncgreco1440** [comment]
IEEE Formatted [music file](https://drive.google.com/file/d/15gd7Rki5F8YdLkD4whpL_8bdSgXuHdij/view?usp=sharing).

**Comment by scriptorian** [comment]
Thanks very much for providing a file - that made it very straightforward.
The file now plays for me. Please can you retest and confirm this is resolved for you?

**Comment by ncgreco1440** [comment]
👍 all good!
