### ISSUE TITLE
Get exact timestamp of audio recording start in with PortAudio

### ISSUE THREAD

**Issue by egormashukov100** [Streampunk/naudiodon#38]
Basically, we record audio and video separately, but afterwards we still need to sync them together, and in order to do that, we need exact timestamp of audio start, and by piping into AudioIO or listening to data events we not getting it right. Port Audio has some delay in releasing chunks.

Fully described problem [here](https://stackoverflow.com/questions/58556891/how-to-get-exact-timestamp-of-audio-recording-start-in-with-portaudio).

**Comment by scriptorian** [comment]
I have added some logic to audio input streams to provide accurate timestamps from portaudio. Unfortunately on the platform I am developing on the portaudio callback does not provide the expected time information so I have had to use the current time at the point the callback runs. This runs in a high priority thread but I would expect there to be jitter, perhaps ~10ms.

**Comment by mattbajorek** [comment]
@scriptorian Thank you for adding the timestamps, but there was no npm release of this commit.  The latest release includes everything but this commit. Would you be able to tag and deploy a new release?

**Comment by scriptorian** [comment]
Sorry to have missed that, done now. v2.2.0 on npm.
