### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mathiasjakobsen** [Streampunk/naudiodon#4]
On the latest version of naudiodon, `getDevices` will throw an exception. I'm on macOS Sierra if that is any help.

```js
var naudiodon = require('naudiodon')
...
console.log(naudiodon.getDevices()) // Uncaught TypeError: Path must be a string. Received undefined
```

I hope you'll be able to help - I'm looking very much forward, to use your great addon.

**Comment by sparkpunkd** [comment]
Thanks for raising this issue. I am travelling this week with no access to my Mac and I will check the issue next week when I return home. 

Note that I just checked on Windows and this function is working OK on that platform.
