### ISSUE TITLE
Segfault once mainthread becomes blocked

### ISSUE THREAD

**Issue by ruohki** [Streampunk/naudiodon#40]
Hey iam trying to implement the lib in an electron app. Sadly when i require the module on the main thread and then open a system dialogbox i end up getting my console spamed with segfaults

```
PID 19756 received SIGSEGV for address: 0xeb37a839
SymInit: Symbol-SearchPath: '.;E:\my-new;E:\my-new\node_modules\electron\dist;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'ruohki'
OS-Version: 10.0.18362 () 0x100-0x1
E:\my-new\node_modules\segfault-handler\src\StackWalker.cpp (941): StackWalker::ShowCallstack
E:\my-new\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFAED958636 (ntdll): (filename not available): RtlIsGenericTableEmpty
00007FFAED94A0D6 (ntdll): (filename not available): RtlRaiseException
00007FFAED94A043 (ntdll): (filename not available): RtlRaiseException
00007FFAEB37A839 (KERNELBASE): (filename not available): RaiseException
00007FFAC131E372 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12D5800 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12D518C (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC134CA15 (Boxcryptor.Ext): (filename not available): DllGetClassObject
00007FFAC1351402 (Boxcryptor.Ext): (filename not available): DllGetClassObject
00007FFAC12CCB83 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12CC948 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12CB59A (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12CB07A (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12CB008 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC12B4CFD (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAC1323C59 (Boxcryptor.Ext): (filename not available): (function-name not available)
00007FFAECC57BD4 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFAED94CED1 (ntdll): (filename not available): RtlUserThreadStart
```

**Comment by scriptorian** [comment]
I don't think this is caused by naudiodon - segfault handler is indicating that the error has come from Boxcryptor. You could try doing without that package as a test or perhaps commenting out the segfault handler in index.js and see if that makes a difference..

**Comment by ruohki** [comment]
it is not the complete stack, i closed down the application wich caused
another running process to cause the issue.

As stated when using this library in electron 6 remote required or in the
main thread. Showing a dialog window (wich seems to block the application)
will end in a segfault

**Comment by scriptorian** [comment]
Is it possible that there is a disagreement on V8 versions? From [electronjs:](https://electronjs.org/docs/development/upgrading-node)

"Chromium and Node.js both depend on V8, and Electron contains only a single copy of V8, so it's important to ensure that the version of V8 chosen is compatible with the build's version of Node.js and Chromium."

**Comment by ruohki** [comment]
Came back to test the lib again. It seems like the stuff happens when you click and move the electron window.

Iam using electron rebuild to have everything build against each other

**Comment by Nithin-anim** [comment]
I also got the same error while implementing the package in electron app.I set up an IPC event where I instantiate a portAudio.AudioIO object.When control reaches that point the app crashes and I get crash.log file with the following contents.I tried commenting the 2 lines as mentioned above but the app still crashes.

> PID 8415 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x000000010e16bfe0 _ZL16segfault_handleriP9__siginfoPv + 304
1   libsystem_platform.dylib            0x00007fff6353d42d _sigtramp + 29
2   ???                                 0x0000000000000000 0x0 + 0
3   Electron Framework                  0x0000000107727020 napi_adjust_external_memory + 1552
4   Electron Framework                  0x0000000102b6b723 _ZN2v88internal13GlobalHandles40InvokeSecondPassPhantomCallbacksFromTaskEv + 371
5   Electron Framework                  0x00000001077b97ab _ZN4node14options_parser13SplitHostPortERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_6vectorIS7_NS5_IS7_EEEE + 77979
6   Electron Framework                  0x00000001077b87c3 _ZN4node14options_parser13SplitHostPortERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_6vectorIS7_NS5_IS7_EEEE + 73907
7   Electron Framework                  0x000000010783e5d4 uv_async_send + 932
8   Electron Framework                  0x000000010784f2eb uv_free_interface_addresses + 2219
9   Electron Framework                  0x000000010783ea51 uv_run + 401
10  Electron Framework                  0x0000000104231631 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 14457553
11  Electron Framework                  0x00000001042b4dd0 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 14996080
12  Electron Framework                  0x00000001042c437b _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15058971
13  Electron Framework                  0x00000001042c4857 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15060215
14  Electron Framework                  0x0000000104323fe3 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15451267
15  Electron Framework                  0x000000010425a79a _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 14625850
16  Electron Framework                  0x000000010432394f _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15449583
17  CoreFoundation                      0x00007fff2be39b21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
18  CoreFoundation                      0x00007fff2be39ac0 __CFRunLoopDoSource0 + 103
19  CoreFoundation                      0x00007fff2be398d4 __CFRunLoopDoSources0 + 209
20  CoreFoundation                      0x00007fff2be38740 __CFRunLoopRun + 1272
21  CoreFoundation                      0x00007fff2be37bd3 CFRunLoopRunSpecific + 499
22  HIToolbox                           0x00007fff2a98d65d RunCurrentEventLoopInMode + 292
23  HIToolbox                           0x00007fff2a98d39d ReceiveNextEventCommon + 600
24  HIToolbox                           0x00007fff2a98d127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
25  AppKit                              0x00007fff28ffdba4 _DPSNextEvent + 990
26  AppKit                              0x00007fff28ffc380 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
27  AppKit                              0x00007fff28fee09e -[NSApplication run] + 658
28  Electron Framework                  0x00000001043247dc _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15453308
29  Electron Framework                  0x0000000104323318 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15447992
30  Electron Framework                  0x00000001042c4d28 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15061448
31  Electron Framework                  0x00000001042969c7 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 14872167

**Comment by ruohki** [comment]
Install the lib into a fresh electron project. Require it in main thread. Try to drag the window... Watch things burn
