### ISSUE TITLE
Allow setting framesPerBuffer through js api

### ISSUE THREAD

**Issue by japj** [Streampunk/naudiodon#43]
Currently the framesPerBuffer is hardcoded in PaContext.cc (it defaults to paFramesPerBufferUnspecified, but is hardcoded to 256 on arm).

Could framesPerBuffer by exposed on the js api in/outOptions part?

This would allow experiments without needing to recompile the C++ module each time.

**Comment by scriptorian** [comment]
v2.2.1 should now have what you need.
