### ISSUE TITLE
Record system output

### ISSUE THREAD

**Issue by filahf** [Streampunk/naudiodon#47]
Hi,

Basically I want to record and stream the system output of the host. If this is possible how do I modify the inoptions to point to an output?

Thanks

**Comment by michaelgira23** [comment]
Hi @filahf! Were you able to record the host's output with naudiodon? I'm trying to do the same thing. Thanks!

**Comment by filahf** [comment]
Hello, yes I was able to record the output by a workaround in windows. Have a look at [Stereo mix](https://winbuzzer.com/2020/04/25/how-to-record-windows-system-audio-with-stereo-mix-xcxwbt/), there are probably alternative solutions for other OS. 

Good luck!

**Comment by igorzgd** [comment]
Hi @filahf can you pls explain/show how u did that on windows?

Thanks.

**Comment by filahf** [comment]
Hello @igorzgd 
I'm sorry but I cant remember how I managed to solve that with naudiodon. In my use case I ended up with the built in API from Electron. You can have a look at my app that stream system output to Sonos smartspeakers.

https://github.com/filahf/budgie-stream

**Comment by igorzgd** [comment]
@filahf Thanks 👍
