### ISSUE TITLE
Buffer underflow on Raspberry Pi

### ISSUE THREAD

**Issue by sparkpunkd** [Streampunk/naudiodon#5]
Receiving a buffer underflow error when trying to play audio on a Raspberry Pi via USB audio device. 

Also, lots of distortion when playing via the headphone jack.

Suggestion from @scriptorian 

> There is a MaxQueue parameter in AudioOut.cc, currently set to 2. You could try upping that. Next you would need to check the pa callback size - if it is only asking for a small amount of data each time that is going to hurt on the RPi. There is a parameter in the paOpenStream call that can affect this if so.

**Comment by WyrdNexus** [comment]
For anyone curious, that's as simple as passing `maxQueue: 8` in the Audio config:
```javascript
portAudio = naudiodon.AudioOutput({
    channelCount: 1,
    maxQueue: 4,
    sampleFormat: naudio.SampleFormat16Bit,
    sampleRate: 48000,
    deviceId: -1
})
```

Note: This can also be caused by `sampleFormat` or `sampleRate` differing between input and output.

**Comment by scriptorian** [comment]
Closing this issue
