### ISSUE TITLE
input overflow error when thread blocks

### ISSUE THREAD

**Issue by mmckegg** [Streampunk/naudiodon#6]
I am trying to capture input audio from device. This works great when the thread is free, but I have noticed that if the thread blocks for a short while, this can cause `portAudio status - input overflow` to be thrown and then the stream stops.

Managed to get the `scratch/inputToFile.js` to reproduce this by adding a _fake sleep_ (loop that takes a long time to complete).

```js
// add to scratch/inputToFile.js
var collection = []

setInterval(() => {
  for (var i = 0; i < 1000000; i++) {
    collection.push(i)
  }
}, 1000)
```

Then after a few seconds, you should see:

```
Error: portAudio status - input overflow 
    at Error (native)
```

I tried messing with the `maxQueue` value: https://github.com/Streampunk/naudiodon/blob/d0d314659bcfcf79d4fd9977fbbd4aee9350fab2/src/AudioIn.cc#L218

But still hitting this.

Any ideas?

**Comment by scriptorian** [comment]
Thanks for this - and for the code to provoke - very helpful!
