### ISSUE TITLE
Reduce latency and constant Underrun errors

### ISSUE THREAD

**Issue by SinanAkkoyun** [Streampunk/naudiodon#84]
Hey!

I need a ultra low latency audio input and output solution. I piped the input stream directly into the output stream and noticed roughly 300-400ms on my desktop (powerful components).

Code:
```ts
ao = AudioIO({
        outOptions: {
          maxQueue: 1,
          channelCount: 2,
          sampleFormat: SampleFormat16Bit,
          sampleRate: 48000,
          deviceId: -1,
          closeOnError: false // Need to cause of underruns...
        }
      })

ai = AudioIO({
      inOptions: {
        maxQueue: 1,
        channelCount: 2,
        sampleFormat: SampleFormat16Bit,
        sampleRate: 48000,
        deviceId: -1, 
        closeOnError: false
      }
    })

try { ao.start() } catch { }
try { ai.start() } catch { }

ai.pipe(ao)
```

This is my setup. Even when deleting the maxQueue option and letting it be default, on top of the latency, I get LOTS of underrun errors? Why is that, this is a direct stream with everything matching?

So, how can I reduce the latency even further?

Thank you very much for the package and for the coming help!

**Comment by SinanAkkoyun** [comment]
Strangely enough, the latency **per instance** is random.
I restarted it and it came down to a latency of a roughly 150ms or so (just guessing by ear) and stays like that for the whole runtime, but when I restart again it sometimes goes up again to 400 to 500ms...

Could this be related with the underrun errors? What can I do to fix that and achieve near zero latency in this setup?

**Comment by SinanAkkoyun** [comment]
```
PortAudio V19.6.0-devel, revision unknown
Input audio options: default device, sample rate 48000, channels 2, bits per sample 16, max queue 1, frames per buffer 0, close on error false
Input device name is default
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
AudioIO: portAudio status - output underflow
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
AudioIO: portAudio status - output underflow
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
AudioIO: portAudio status - output underflow
```

**Comment by shroomjaks** [comment]
Getting underflow errors too

**Comment by SinanAkkoyun** [comment]
I switched to node-speaker
